### ISSUE TITLE
Chef can no longer write logs with 1.7.0

### ISSUE THREAD

**Issue by viyh** [chef/mixlib-log#17]
As up upgrading from mixlib-log 1.6.0 to 1.7.0, many of these messages are spat out during a Chef-client run:

log writing failed. closed stream

The chef-client logs are not written. Downgrading to 1.6.0 fixes the issue. Chef version is 12.6.0 and also tried with 12.12.15 with bad results.

**Comment by thommay** [comment]
Are you doing anything special with your log config?

**Comment by thommay** [comment]
(I would not upgrade mixlib-log in a deployed chef version unless there's a really good reason to, which is not to say there's not a bug)

**Comment by viyh** [comment]
I'm not doing anything special with the logging config. I did not upgrade mixlib-log. Version 1.7.0 installed automatically with an install of Chef 12.6.0 on a new EC2 instance. I had to manually downgrade mixlib-log to 1.6.0 to make Chef work without error.

**Comment by thommay** [comment]
I can't reproduce this with the chef 12.13.28 omnibus build and some basic cookbooks. Are you seeing the problem immediately, or with a daemonised chef-client?

**Comment by twk3** [comment]
I'm seeing this same issue with an omnibus run, on Chef 12.10.24, where chef is being installed using rubygems gem install. The chef gem has a runtime dependency of mixlib-log set as ~> 1.3

**Comment by viyh** [comment]
I install the Chef gem, then run chef-client via cron un-daemonized and see the problem immediately.

**Comment by lamont-granquist** [comment]
also unable to replicate with omnibus builds

**Comment by lamont-granquist** [comment]
so we've got three strikeouts trying to repro this internally...

we'll need to know something like:

- what o/s distro and version
- what ruby version and how it was installed
- exact steps taken to install chef
- what command line is being run
- what the contents of /etc/chef/client.rb are, if any
- complete output of the failure
- stacktrace.out if any gets dumped
- someway to determine the running gemset:
    - gem list would be useful
    - a Gemfile and Gemfile.lock that pinned the gem versions and ruby version would also be useful if its not an omnibus install

**Comment by mwrock** [comment]
I finally managed to repro this after several permutations. Here is my setup:

* Windows 2012R2 (we have gotten reports on both windows and non windows)
* Standard omnibus install of latest 12.13.30
* Bootstrapped to a server (I was unable to repro via chef-solo)
* client.rb with `log_location` pointing to a file. (`STDOUT` did not repro)

**Comment by mwrock** [comment]
```
S C:\Windows\system32> .\notepad.exe C:\chef\client.rb
S C:\Windows\system32> chef-client -VV
:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb:230:in `parse_options': invalid opt
on: -VV (OptionParser::InvalidOption)
       from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.30-universal-mingw32/lib/chef/application.rb:8
:in `configure_chef'
       from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.30-universal-mingw32/lib/chef/application.rb:4
:in `reconfigure'
       from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.30-universal-mingw32/lib/chef/application/clie
t.rb:313:in `reconfigure'
       from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.30-universal-mingw32/lib/chef/application.rb:5
:in `run'
       from C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.30-universal-mingw32/bin/chef-client:26:in `<t
p (required)>'
       from C:/opscode/chef/bin/chef-client:64:in `load'
       from C:/opscode/chef/bin/chef-client:64:in `<main>'
```

**Comment by lamont-granquist** [comment]
simpler repo on Ubuntu with omnibus-current:

`chef-client --force-logger -L /tmp/chef.out`

**Comment by thommay** [comment]
Thanks everyone, fixed ohai has been released.
